WITH trap_data AS (
SELECT
  FORMAT_DATE('%Y-Q%Q', DATE(STRIKE_AT)) AS YEAR_QUARTER,
  TRAP_ID,
  LOCATION_ID,
  FULL_ADDRESS,
  SUBURB_LOCALITY,
  TOWN_CITY,
  TERRITORIAL_AUTHORITY,
  ACTIVITY_TYPE,
  TRAP_LATITUDE,
  TRAP_LONGITUDE,
  STRIKE_AT
FROM {{ ref('int_trap_details')}}
WHERE ACTIVITY_TYPE = 'STRIKE' AND STRIKE_AT >= '2017-01-01'
)
SELECT
  YEAR_QUARTER,
  TRAP_ID,
  LOCATION_ID,
  FULL_ADDRESS,
  SUBURB_LOCALITY,
  TOWN_CITY,
  TERRITORIAL_AUTHORITY,
  ACTIVITY_TYPE,
  TRAP_LATITUDE,
  TRAP_LONGITUDE,
  COUNT(ACTIVITY_TYPE) NUM_KILLS,
  COUNT(DISTINCT TRAP_ID) NUM_TRAPS
FROM trap_data
GROUP BY
  YEAR_QUARTER,
  TRAP_ID,
  LOCATION_ID,
  FULL_ADDRESS,
  SUBURB_LOCALITY,
  TOWN_CITY,
  TERRITORIAL_AUTHORITY,
  ACTIVITY_TYPE,
  TRAP_LATITUDE,
  TRAP_LONGITUDE
ORDER BY
  YEAR_QUARTER,
  TERRITORIAL_AUTHORITY,
  NUM_TRAPS DESC,
  NUM_KILLS DESC
